CREATE TABLE IF NOT EXISTS book_information (
     management_id INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
     title VARCHAR(20) NOT NULL,  
     title_kana VARCHAR(20)NOT NULL,
     number_of_turns INT(3) NOT NULL,
     author_name VARCHAR(10) NOT NULL,
     author_name_kana VARCHAR(10) NOT NULL,
     publisher_name VARCHAR(15) NOT NULL,
     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 );
 
CREATE TABLE IF NOT EXISTS evaluation (
     management_id INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
     evaluation TINYINT(1) NOT NULL,  
     comment VARCHAR(100)NOT NULL,
     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 );
 